title: "Md Belal Islam"
description: "DevOps Engineering Manager Portfolio"
baseurl: "" # for GitHub Pages keep empty
url: "https://Belalgit.github.io"

theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
